Clarify Resource Authorization is a refinement of WAC/Solid
fcrepo/fcrepo-specification pull request #116
Opened 2017-05-11 18:47 UTC by barmintor

fixes #101

2017-05-11 20:13 UTC, ajs6f approved these changes

2017-05-11 20:15 UTC, acoburn commented on index.html
> +          The linked Access Control List Resource (ACL) for a controlled resource by a conforming server MUST itself be a LDPRS. This ACL resource SHOULD be located in the same server as the controll
nit picking, but it's nice to wrap the lines at some sensible length to make reading them easier. (There are other advantages, too!)

2017-05-11 20:29 UTC, barmintor commented on index.html
> +          The linked Access Control List Resource (ACL) for a controlled resource by a conforming server MUST itself be a LDPRS. This ACL resource SHOULD be located in the same server as the controll
Needed to rebase, but corrected now. Thanks!

2017-05-11 20:31 UTC, acoburn approved these changes

2017-05-11 20:47 UTC, escowles commented
👍

2017-05-15 16:17 UTC, zimeon commented
:+1:

2017-05-15 16:38 UTC, awoods requested changes

2017-05-15 16:38 UTC, awoods commented on index.html
> -        resource has its own access control resource and so on. Implementations MUST make access
In order to ensure the use of `Link: rel="acl"`, I would prefer to keep the follow language in the spec:
> Implementations MUST make access control resources discoverable via the <code>Link: rel="acl"</code> HTTP header, as discussed <a href="https://github.com/solid/web-access-control-spec#acl-resource-location-discovery">here</a>

2017-05-15 16:40 UTC, acoburn commented on index.html
> -        resource has its own access control resource and so on. Implementations MUST make access
Yes, but please change the formatting. A "click here" link is really not best practice.

2017-05-15 20:16 UTC, barmintor commented on index.html
> -        resource has its own access control resource and so on. Implementations MUST make access
I added a new section to (re)capture this requirement.

2017-05-17 15:16 UTC, awoods approved these changes

2017-05-17 15:17 UTC, awoods commented
@escowles / @zimeon : If you are ok with the recent updates, I suggest we move this PR forward.

2017-05-17 15:20 UTC, escowles commented
@awoods Yes, I am still 👍  on this PR.

2017-05-17 15:26 UTC, barmintor commented
@dannylamb ?

2017-05-17 15:27 UTC, dannylamb approved these changes

2017-05-17 15:28 UTC, dannylamb commented
Im good with this :+1:

2017-05-18 05:38 UTC, zimeon approved these changes

2017-05-18 13:46 UTC, merged