Add notion of default ACL, every controlled resource must have ACL
fcrepo/fcrepo-specification pull request #173
Opened 2017-07-19 21:23 UTC by zimeon

Fixes #163

2017-07-19 21:26 UTC, awoods commented
Minor Travis issue with line length.

2017-07-19 21:40 UTC, zimeon commented
Thanks @awoods - was in process of fixing, and now fixed

2017-07-19 21:47 UTC, awoods requested changes

2017-07-19 21:47 UTC, awoods commented on index.html
> +          in [[!SOLIDWEBAC]].
Recommend adding a direct link to: https://github.com/solid/web-access-control-spec#acl-resource-location-discovery

2017-07-20 01:04 UTC, zimeon commented on index.html
> +          in [[!SOLIDWEBAC]].
Good call, will update PR

2017-07-20 11:41 UTC, escowles commented on index.html
> +          The Access Control List Resource (ACL) for a controlled resource on conforming server MUST itself be
Minor edit: can you change "on conforming server" to "on a conforming server"?

2017-07-20 11:42 UTC, escowles approved these changes
👍  Other than a very minor edit, this looks good to me.

2017-07-20 13:01 UTC, zimeon commented on index.html
> +          The Access Control List Resource (ACL) for a controlled resource on conforming server MUST itself be
Thanks @escowles, will update

2017-07-20 13:50 UTC, awoods approved these changes

2017-07-20 15:55 UTC, acoburn commented
One question about the default ACL and the corresponding link header. If a server `MUST` supply a default ACL for controlled resources that don't have an ACL defined in the relevant hierarchy, if follows that the server `MUST` also provide a link to that ACL in the HTTP response headers. Does that imply that the default ACL must be dereferencable?

2017-07-20 15:59 UTC, zimeon commented
@acoburn - yes, I think so

2017-07-20 16:04 UTC, acoburn commented
@zimeon thanks! (n.b. this is another difference w/ the current Fedora WebAC module, but that's entirely OK from my perspective).

2017-07-20 16:13 UTC, zimeon commented
Have created #175 to separate the decision about saying default MUST be resolvable

2017-07-25 16:47 UTC, dannylamb approved these changes

2017-07-25 17:43 UTC, barmintor approved these changes

2017-07-25 19:27 UTC, merged