Do not use ldp: prefix for Link type value
fcrepo/fcrepo-specification pull request #190
Opened 2017-08-10 19:55 UTC by zimeon

... because one has to specify the full URI in the `Link` header

2017-08-13 18:31 UTC, awoods requested changes
There appears to be a line-length issue.

2017-08-14 20:42 UTC, awoods approved these changes

2017-08-14 20:43 UTC, awoods commented
@fcrepo/editors : This is a minor update... looking for one more editor to merge it.

2017-08-14 20:46 UTC, escowles approved these changes

2017-08-16 18:50 UTC, barmintor commented
:+1:

2017-08-18 18:53 UTC, merged