Add section on ACL linking on resource creation
fcrepo/fcrepo-specification pull request #214
Opened 2017-09-08 20:17 UTC by zimeon

Fixes #176.

Adds a section "ACL linking on resource creation" based on https://github.com/fcrepo/fcrepo-specification/issues/176#issuecomment-319149546 . This places a requirement on servers to recognize the `Link: rel="acl"` header on resource creation, whether or not they support specification of an ACL in this way. If they don't support it, response will always be 4xx. It does not preclude other ways of linking a resource to an ACL.

2017-09-08 20:46 UTC, birkland commented
(Just trying to clarify that I understand) 

If no `Link: rel="acl"` is provided by the client, given our understanding that the semantics of the acl rel [point to the resource's own ACL](https://github.com/fcrepo/fcrepo-specification/pull/198#issuecomment-326126675) and the acl rel MUST always be present, think we can conclude that the server will either create such a resource, or link to a nonexistent resource that the client can discover and `PUT` in order to create a resource's ACL.  So #176 already has an implicit solution, I believe.

So, is this PR is adding additional functionality that optionally allows the client to pre-specify the location of the resource's own individual ACL, by pointing it to a resource that already exists?  If a repository returns a success response code, then would the `rel=acl` of the newly created resource inherently be identical to the one specified in the request?  Is the intent, therefore, to let the server optionally provide a mechanism by which many resources can point to (and therefore share) the same ACL resource, explicitly?

2017-09-09 21:07 UTC, acoburn commented
👎  for the reasons outlined here: https://groups.google.com/forum/#!topic/fedora-tech/VLDQOwhhTqY

2017-09-10 11:05 UTC, escowles submitted a review, later dismissed

2017-09-15 14:21 UTC, awoods submitted a review, later dismissed

2017-09-26 16:48 UTC, zimeon commented
Rebased onto current master to fix merge conflict. No change to addition. Apologies for dismissing your reviews @escowles and @awoods

2017-09-26 21:42 UTC, awoods approved these changes

2017-09-27 17:26 UTC, escowles submitted a review, later dismissed

2017-10-04 19:15 UTC, dannylamb submitted a review, later dismissed

2017-10-11 17:41 UTC, barmintor commented
Worth noting: LDP does not require failing with 4xx (just failing) when discussing interaction model support. Should the 4xx requirement be softened to SHOULD, and the MUST reserved for failure in general?

2017-10-18 18:43 UTC, escowles commented
I agree with @barmintor here: we could change the language to "The server MUST fail the request if it isn't able to create..."

2017-10-21 14:58 UTC, awoods commented
I agree with @barmintor that as it relates to supporting requested interactions model when creating a resource, the LDP spec language states that ["the server MUST fail the request"](https://www.w3.org/TR/ldp/#ldpc-post-createrdf), without mention of constraints.

However, this PR seems less related to interaction models and more related to the general scenario of ["a server that refuses resource creation"](https://www.w3.org/TR/ldp/#ldpr-gen-pubclireqs). Without a `constrainedBy` Link header in the response, it may be difficult for the client to determine why the request failed.

As a side note, it seems that a `constrainedBy` Link header in failed interaction model scenarios would also be helpful to the client.

2017-10-29 21:24 UTC, awoods commented
@barmintor / @escowles : I believe we are in agreement with the bulk of this PR, the open question is in how to handle the situation where the client-provided `Link: rel="acl"` is not permitted.
1. The current text says: MUST fail with 4xx status and link to `constrainedBy` document.
1. I believe @barmintor's suggestion is to change the above MUST to SHOULD.
1. I believe @escowles' suggestion is to remove the mention of 4xx, but otherwise leave the text as is.

[My inclination](https://github.com/fcrepo/fcrepo-specification/pull/214#issuecomment-338408358) is to leave the wording as is; however, I recall @barmintor had a compeling characterization of the use of `MUST`, `SHOULD`, and `MAY`. 
@barmintor , if you could link to a definition of your conceptualization of the RFC keywords, that may help inform the usage here.

2017-10-29 21:25 UTC, awoods requested changes
Pending @escowles / @barmintor input.

2017-11-01 21:09 UTC, zimeon commented
Rereading @barmintor's https://github.com/fcrepo/fcrepo-specification/pull/214#issuecomment-335890685 -- I do not understand what failing means if not 4xx response. What am I missing?

2017-11-01 21:12 UTC, escowles commented
@zimeon I believe @barmintor was advocating for saying "The server MUST fail the request..." instead of "The server MUST respond with a 4xx range status code (e.g. 409 Conflict)..."

2017-11-01 21:14 UTC, zimeon commented
@escowles I agree with your reading but I don't know how to fail the request _without_ returning 4xx

2017-11-01 21:22 UTC, escowles commented
@zimeon I agree — as an implementer, I would definitely read either wording to mean I should not create the resource, and instead return a 4xx error.  So it's more about style and specificity, not what the implementation should actually do.

2017-11-01 21:31 UTC, zimeon commented
@escowles - OK, then I disagree with @barmintor's requested change on style grounds: every place else we say fail or reject we also specify a 4xx (or more specific) response, so we should here too.

2017-11-01 23:15 UTC, awoods submitted a review, later dismissed

2017-11-05 04:16 UTC, barmintor commented
@zimeon the reason I referred to the interaction model passage from LDP was that it was a comparable instance of intended resource characteristics included in `Link` request headers. I don't think it matters whether the failure is a 4xx, or a 5xx, etc. I also would probably return a 4xx, but I want to approach all the tightening of LDP requirements with clear intention.

2017-11-05 14:24 UTC, zimeon commented
Thanks @barmintor, I hadn't understood that was what you had in mind. I tend to think of 5xx as indicating lower level issues only but I agree that LDP does not specify 4xx in this case. I have updated the PR to permit 4xx or 5xx.

2017-11-05 14:51 UTC, barmintor commented
Thanks for your patience, @zimeon!

2017-11-05 14:52 UTC, barmintor approved these changes

2017-11-05 15:59 UTC, escowles approved these changes

2017-11-05 16:51 UTC, awoods approved these changes

2017-11-08 15:58 UTC, dannylamb approved these changes

2017-11-08 15:59 UTC, merged