Add Acknowledgments
fcrepo/fcrepo-specification pull request #272
Opened 2017-11-22 19:25 UTC by awoods

Resolves: https://github.com/fcrepo/fcrepo-specification/issues/268

2017-11-22 19:28 UTC, escowles submitted a review, later dismissed

2017-11-22 20:56 UTC, zimeon requested changes

2017-11-22 20:56 UTC, zimeon commented on index.html
> +        Sarven Capadisli, Herbert Van de Sompel, the Fedora Repository, Islandora and Samvera communities.
The communities aren't people, and there is an ambiguity in the list as to which elements "communities" applies to. Perhaps:

> Sarven Capadisli, Herbert Van de Sompel, **and members of** the Fedora Repository, Islandora and Samvera communities.

2017-11-22 21:10 UTC, dannylamb submitted a review, later dismissed
Conditionally approving once @zimeon's feedback is addressed.

2017-11-22 21:39 UTC, escowles approved these changes

2017-11-22 21:50 UTC, awoods commented
@zimeon : changes made:
https://github.com/fcrepo/fcrepo-specification/pull/272/commits/ce382bdc32f9566cc8813812ed73c87b74dcf48e
..based on comment: 
https://github.com/fcrepo/fcrepo-specification/pull/272#pullrequestreview-78576610

2017-11-22 21:53 UTC, zimeon approved these changes

2017-11-27 15:17 UTC, dannylamb approved these changes
:shipit:

2017-11-27 15:17 UTC, merged