Editorial clean-up (section 5)
fcrepo/fcrepo-specification pull request #366
Opened 2018-05-09 17:07 UTC by awoods

* Remove wording: 'Implementation of support'
* Add 'but not acl:Write' when detailing acl:Append expectations

Resolves part of: https://github.com/fcrepo/fcrepo-specification/issues/358

2018-05-09 19:15 UTC, zimeon submitted a review, later dismissed

2018-05-11 13:53 UTC, escowles submitted a review, later dismissed

2018-05-11 13:57 UTC, dannylamb submitted a review, later dismissed

2018-05-22 19:14 UTC, barmintor requested changes

2018-05-22 19:14 UTC, barmintor commented on index.html
> +          requires retrieval of one or more Group Listing documents. Security implications should be considered if
The subject of this sentence is now plural, so "require"?

2018-05-22 21:29 UTC, barmintor approved these changes

2018-05-23 05:23 UTC, zimeon approved these changes

2018-05-23 13:06 UTC, escowles approved these changes

2018-05-23 19:05 UTC, merged