Remove requirement for constrainedBy on successful POST
fcrepo/fcrepo-specification pull request #394
Opened 2018-08-29 19:40 UTC by zimeon

Closes #380

2018-08-29 19:41 UTC, escowles approved these changes

2018-08-29 19:46 UTC, awoods requested changes
Should the `Non-normative` text in [section 4.3.3.2](https://fedora.info/2018/06/25/spec/#ldpcv-post-not-allowed) also be updated?

2018-08-29 19:58 UTC, awoods approved these changes

2018-08-30 17:53 UTC, dannylamb approved these changes

2018-09-11 21:38 UTC, merged